name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ matrix.os[0] }}
    strategy:
      matrix:
        os: [[macos-latest, bash], [ubuntu-latest, bash], [windows-latest, msys2]]
      fail-fast: false
    defaults:
     run:
      shell: ${{ matrix.os[1] }} {0}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Ubuntu packages
      if: matrix.os[0] == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get -y install texinfo bison flex gettext libgmp3-dev libmpfr-dev libmpc-dev
        echo "MSYSTEM=x64" >> $GITHUB_ENV

    - name: Install macOS packages
      if: matrix.os[0] == 'macos-latest'
      run: |
        brew update
        brew install texinfo bison flex gnu-sed gsl gmp mpfr libmpc
        echo "MSYSTEM=x64" >> $GITHUB_ENV

    - name: Install MSYS2 packages
      if: matrix.os[0] == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
        install: |
          base-devel git texinfo flex bison patch binutils gcc mpc-devel tar
          cmake mingw-w64-x86_64-extra-cmake-modules make mingw-w64-x86_64-libogg
        update: true

    - name: Runs all the stages in the shell
      continue-on-error: false
      run: |
        export PS2DEV=$PWD/ps2dev
        export PS2SDK=$PS2DEV/ps2sdk
        export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
        export PATH="/usr/local/opt/bison/bin:$PATH"
        export PATH=$PATH:$PS2DEV/bin:$PS2DEV/ee/bin:$PS2DEV/iop/bin:$PS2DEV/dvp/bin:$PS2SDK/bin
        ./toolchain.sh
